version: "3.9"

services:

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Danilo2001
      POSTGRES_DB: Homework
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/DB.sql:/docker-entrypoint-initdb.d/DB.sql

  # gRPC Server
  grpc_server:
    build:
      context: ./server 
    container_name: grpc_server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Danilo2001
      DATABASE_NAME: Homework
    ports:
      - "50051:50051"

  # Data Collector
  datacollector:
    build:
      context: ./data_collector
    container_name: datacollector
    restart: always
    depends_on:
      - db
      - kafka-broker
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Danilo2001
      DATABASE_NAME: Homework
      KAFKA_BROKER: kafka-broker:9092  # Assicurati di utilizzare il nome del servizio Kafka per la connessione

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka
  kafka-broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    restart: always



  alert_system:
    build: ./alert_system
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Danilo2001
      - DATABASE_NAME=Homework
      - KAFKA_BROKER=kafka-broker:9092
    depends_on:
      - db
      - kafka-broker
    restart: always




volumes:
  db_data: