global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alert_manager:9093'

scrape_configs:
  - job_name: 'prometheus'   
    scrape_interval: 25s    
    metrics_path: '/metrics' 
    scheme: 'http'
    static_configs:
         - targets:
           - prometheus:9090          
           - grpc_server:9999
           - datacollector:50056
           - alert_system:50057 
           - alert_notifier_system:50058