apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      imagePullSecrets:
      - name: dockerhub-secret 
      containers:
      - name: alertmanager-container
        image: danilo238/gudam:gudam-alert_manager
        args:
        - "--config.file=/etc/alertmanager/config.yml"
        - "--storage.path=/alertmanager"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager/config.yml
          subPath: config.yml
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-storage
        persistentVolumeClaim:
          claimName: alertmanager-persistent-storage

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'daniloverde2001@gmail.com'
      smtp_auth_username: 'daniloverde2001@gmail.com'
      smtp_auth_password: 'kbpe tuzx feke psrn'
      smtp_require_tls: true

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'email_notifications'

    receivers:
      - name: 'email_notifications'
        email_configs:
          - to: 'danylaus98@gmail.com'
            send_resolved: true

---

apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  labels:
    app: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
  - name: http
    protocol: TCP
    port: 9093
    targetPort: 9093

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-persistent-storage
  labels:
    app: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
