apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 postgres-db-service 5432; do echo "Waiting for PostgreSQL..."; sleep 5; done']
      containers:
      - name: grpc-server
        image: danilo238/gudam:gudam-grpc_server
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: DATABASE_HOST
          value: "postgres-db-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "Danilo2001"
        - name: DATABASE_NAME
          value: "Homework"
        ports:
        - containerPort: 50051


---


apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  type: NodePort
  selector:
    app: grpc-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
    nodePort: 30051 